### ISSUE TITLE
Minor issue in DPAM.py

### ISSUE THREAD

**Issue by ssrb19** [CongLabCode/DPAM#4]
Right now the code reads:
` if basedir[0] != '/':
    basedir = os.getcwd() + basedir`

It should read:
` if basedir[0] != '/':
    basedir = os.getcwd() + '/' + basedir`

**Comment by CongLabCode** [comment]
Thanks for pointing out the error

**Comment by ssrb19** [comment]
Thanks for fixing it. The code now runs quite quickly. Maybe MMSeqs2 will help it a bit more. It's taking on average 6-10 mins per protein on 16 CPUs.
