### ISSUE TITLE
Linker regions between domains

### ISSUE THREAD

**Issue by hirenj** [CongLabCode/DPAM#6]
Hi,

Thanks for the work you've put into this - it looks really useful!

I've been looking at extracting linker regions between domains using DPAM, and I noticed something a little odd. If you plot the length of a linker region (i.e., in between the end of a domain and before the start of the next domain), it looks a lot like the lengths of linkers is a multiple of 5 (just showing linkers up to 100 amino acids long).

<img width="586" alt="image" src="https://user-images.githubusercontent.com/155605/207619857-8ed8065c-6a17-4e29-b864-f3624d50014e.png">

It looks suspiciously like an artefact. Is there any way that multiples of 5 snuck in to the domain calling somehow? I'm using the pre-generated Homo sapiens DPAM data from this repository, and extracting the domain starts/ends into a big table, which I then transform.

**Comment by CongLabCode** [comment]
Yes, I think it is an artefact.  We used 5 amino acids as segments length
"We considered a segment of **Xlength (tested values: 5,10; optimized value: 5)** residues to be disordered if the total number of PAE neighbors for residues in this segment is no more than Xneighbor (tested values: 5, 10, 15, 20, 25; optimized value: 10). ".  But you can modify it in our scripts from 5 to 1. It will improve detection accuracy but will be more computational intensive and take more time to run.

**Comment by hirenj** [comment]
Great, that's good to know! I'll re-run this with the shorter segment lengths, and hopefully it'll all work!
